#pragma checksum "..\..\..\..\Pages\Admin\AdminWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "C6903226E13F5765AF4FE96EE2E8AD8CD03937E446DED39BEB2B255B5ED805A6"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Admin;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Admin {
    
    
    /// <summary>
    /// AdminWindow
    /// </summary>
    public partial class AdminWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 21 "..\..\..\..\Pages\Admin\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SettingsButton;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\..\Pages\Admin\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ReviewLogfilesButton;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\Pages\Admin\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AlterRateFeeTable;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\Pages\Admin\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AlterCarrierData;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\Pages\Admin\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AlterRouteTable;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\Pages\Admin\AdminWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BackupDatabase;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TMS;component/pages/admin/adminwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Pages\Admin\AdminWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.SettingsButton = ((System.Windows.Controls.Button)(target));
            
            #line 21 "..\..\..\..\Pages\Admin\AdminWindow.xaml"
            this.SettingsButton.Click += new System.Windows.RoutedEventHandler(this.SettingsButton_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.ReviewLogfilesButton = ((System.Windows.Controls.Button)(target));
            
            #line 22 "..\..\..\..\Pages\Admin\AdminWindow.xaml"
            this.ReviewLogfilesButton.Click += new System.Windows.RoutedEventHandler(this.ReviewLogfilesButton_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.AlterRateFeeTable = ((System.Windows.Controls.Button)(target));
            
            #line 23 "..\..\..\..\Pages\Admin\AdminWindow.xaml"
            this.AlterRateFeeTable.Click += new System.Windows.RoutedEventHandler(this.AlterRateFeeTable_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.AlterCarrierData = ((System.Windows.Controls.Button)(target));
            
            #line 24 "..\..\..\..\Pages\Admin\AdminWindow.xaml"
            this.AlterCarrierData.Click += new System.Windows.RoutedEventHandler(this.AlterCarrierData_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.AlterRouteTable = ((System.Windows.Controls.Button)(target));
            
            #line 25 "..\..\..\..\Pages\Admin\AdminWindow.xaml"
            this.AlterRouteTable.Click += new System.Windows.RoutedEventHandler(this.AlterRouteTable_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.BackupDatabase = ((System.Windows.Controls.Button)(target));
            
            #line 26 "..\..\..\..\Pages\Admin\AdminWindow.xaml"
            this.BackupDatabase.Click += new System.Windows.RoutedEventHandler(this.BackupDatabase_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            
            #line 28 "..\..\..\..\Pages\Admin\AdminWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

