#pragma checksum "..\..\..\..\Pages\Admin\AlterRateFeeTableWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "594E1BA7D9CB5EB1A00C7AC937A339316803A45F624565C1106E33A17E064479"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using TMS.Pages.Admin;


namespace TMS.Pages.Admin {
    
    
    /// <summary>
    /// AlterRateFeeTableWindow
    /// </summary>
    public partial class AlterRateFeeTableWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 19 "..\..\..\..\Pages\Admin\AlterRateFeeTableWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RTInsertButton;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\..\Pages\Admin\AlterRateFeeTableWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RTUpdateButton;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\Pages\Admin\AlterRateFeeTableWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RTDeleteButton;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TMS;component/pages/admin/alterratefeetablewindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Pages\Admin\AlterRateFeeTableWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.RTInsertButton = ((System.Windows.Controls.Button)(target));
            
            #line 19 "..\..\..\..\Pages\Admin\AlterRateFeeTableWindow.xaml"
            this.RTInsertButton.Click += new System.Windows.RoutedEventHandler(this.RTInsertButton_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.RTUpdateButton = ((System.Windows.Controls.Button)(target));
            return;
            case 3:
            this.RTDeleteButton = ((System.Windows.Controls.Button)(target));
            
            #line 21 "..\..\..\..\Pages\Admin\AlterRateFeeTableWindow.xaml"
            this.RTDeleteButton.Click += new System.Windows.RoutedEventHandler(this.RTDeleteButton_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

