#pragma checksum "..\..\..\..\Pages\Admin\BackupDatabasePopUp.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "54FEF0E98A32AF7C7FFA511AFBA0AAC8BBFA168855EB9B34E175BE85C1A70043"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Admin;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Admin {
    
    
    /// <summary>
    /// BackupDatabasePopUp
    /// </summary>
    public partial class BackupDatabasePopUp : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 21 "..\..\..\..\Pages\Admin\BackupDatabasePopUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button OkBackup;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\..\Pages\Admin\BackupDatabasePopUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button CancelBackup;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\Pages\Admin\BackupDatabasePopUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox DatabaseBackupDirectoryTextBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TMS;component/pages/admin/backupdatabasepopup.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Pages\Admin\BackupDatabasePopUp.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.OkBackup = ((System.Windows.Controls.Button)(target));
            
            #line 21 "..\..\..\..\Pages\Admin\BackupDatabasePopUp.xaml"
            this.OkBackup.Click += new System.Windows.RoutedEventHandler(this.OkBackup_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.CancelBackup = ((System.Windows.Controls.Button)(target));
            
            #line 22 "..\..\..\..\Pages\Admin\BackupDatabasePopUp.xaml"
            this.CancelBackup.Click += new System.Windows.RoutedEventHandler(this.CancelBackup_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.DatabaseBackupDirectoryTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

