#pragma checksum "..\..\..\..\Pages\Buyer\BuyerWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "CC37D5E7510B523288AEA38EEF5DF08BB620A763794B3881D94559B2DE4E0CBB"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using TMS.Pages;


namespace TMS.Pages {
    
    
    /// <summary>
    /// BuyerWindow
    /// </summary>
    public partial class BuyerWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 10 "..\..\..\..\Pages\Buyer\BuyerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid dataGrid1;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\Pages\Buyer\BuyerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox ContractsListBox;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\Pages\Buyer\BuyerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox CustomersListBox;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\Pages\Buyer\BuyerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox CompletedOrderListBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TMS;component/pages/buyer/buyerwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Pages\Buyer\BuyerWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.dataGrid1 = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 2:
            
            #line 19 "..\..\..\..\Pages\Buyer\BuyerWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ViewContracts_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 20 "..\..\..\..\Pages\Buyer\BuyerWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ViewCustomers_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 21 "..\..\..\..\Pages\Buyer\BuyerWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ViewCompletedOrders_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            
            #line 22 "..\..\..\..\Pages\Buyer\BuyerWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CreateOrder_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 23 "..\..\..\..\Pages\Buyer\BuyerWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AddCustomer_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            
            #line 24 "..\..\..\..\Pages\Buyer\BuyerWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.GenerateInvoice_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.ContractsListBox = ((System.Windows.Controls.ListBox)(target));
            
            #line 25 "..\..\..\..\Pages\Buyer\BuyerWindow.xaml"
            this.ContractsListBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ContractsListBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 9:
            this.CustomersListBox = ((System.Windows.Controls.ListBox)(target));
            
            #line 26 "..\..\..\..\Pages\Buyer\BuyerWindow.xaml"
            this.CustomersListBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CustomersListBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 10:
            this.CompletedOrderListBox = ((System.Windows.Controls.ListBox)(target));
            
            #line 27 "..\..\..\..\Pages\Buyer\BuyerWindow.xaml"
            this.CompletedOrderListBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CompletedOrderListBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 11:
            
            #line 28 "..\..\..\..\Pages\Buyer\BuyerWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

