#pragma checksum "..\..\..\..\Pages\Admin\ConnectionSettingsPopUp.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "EE21E8A865E878ED06DCAE7B15A0FEF07618C43CF8627EB56CCFD0AC996A290E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Admin;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Admin {
    
    
    /// <summary>
    /// ConnectionSettingsPopUp
    /// </summary>
    public partial class ConnectionSettingsPopUp : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 22 "..\..\..\..\Pages\Admin\ConnectionSettingsPopUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox IPTextBox;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\Pages\Admin\ConnectionSettingsPopUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PortTextBox;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\Pages\Admin\ConnectionSettingsPopUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SetConnectionButton;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\Pages\Admin\ConnectionSettingsPopUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button CancelConnectionButton;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TMS;component/pages/admin/connectionsettingspopup.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Pages\Admin\ConnectionSettingsPopUp.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.IPTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 2:
            this.PortTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.SetConnectionButton = ((System.Windows.Controls.Button)(target));
            
            #line 27 "..\..\..\..\Pages\Admin\ConnectionSettingsPopUp.xaml"
            this.SetConnectionButton.Click += new System.Windows.RoutedEventHandler(this.SetConnectionButton_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.CancelConnectionButton = ((System.Windows.Controls.Button)(target));
            
            #line 28 "..\..\..\..\Pages\Admin\ConnectionSettingsPopUp.xaml"
            this.CancelConnectionButton.Click += new System.Windows.RoutedEventHandler(this.CancelConnectionButton_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

