#pragma checksum "..\..\..\..\Pages\Admin\DeleteRatePopUp.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "6F151DB1733FDFA304A99BF7C21857A0E73BDC559B0DA5FF4B04432C94D9D6F8"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using TMS.Pages.Admin;


namespace TMS.Pages.Admin {
    
    
    /// <summary>
    /// DeleteRatePopUp
    /// </summary>
    public partial class DeleteRatePopUp : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 22 "..\..\..\..\Pages\Admin\DeleteRatePopUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DeleteRate;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\Pages\Admin\DeleteRatePopUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button CancelRate;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\Pages\Admin\DeleteRatePopUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox DeleteRateTextBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TMS;component/pages/admin/deleteratepopup.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Pages\Admin\DeleteRatePopUp.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.DeleteRate = ((System.Windows.Controls.Button)(target));
            
            #line 22 "..\..\..\..\Pages\Admin\DeleteRatePopUp.xaml"
            this.DeleteRate.Click += new System.Windows.RoutedEventHandler(this.DeleteRate_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.CancelRate = ((System.Windows.Controls.Button)(target));
            
            #line 23 "..\..\..\..\Pages\Admin\DeleteRatePopUp.xaml"
            this.CancelRate.Click += new System.Windows.RoutedEventHandler(this.CancelRate_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.DeleteRateTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

