#pragma checksum "..\..\..\..\Pages\Admin\InsertRatePopUp.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "2A157C0B4DE3A52F7B2FDD330B47608A6E2F6F612C53C1B0C4638518C53C348F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using TMS.Pages.Admin;


namespace TMS.Pages.Admin {
    
    
    /// <summary>
    /// InsertRatePopUp
    /// </summary>
    public partial class InsertRatePopUp : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 18 "..\..\..\..\Pages\Admin\InsertRatePopUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button InsertRateButton;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\..\Pages\Admin\InsertRatePopUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button CancelRateButton;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\Pages\Admin\InsertRatePopUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ClientNameTextBox;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\Pages\Admin\InsertRatePopUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox dCityTextBox;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\Pages\Admin\InsertRatePopUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ftlaTextBox;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\Pages\Admin\InsertRatePopUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ltlaTextBox;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\..\Pages\Admin\InsertRatePopUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ftlRateTextBox;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\Pages\Admin\InsertRatePopUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox reefChargeTextBox;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\..\Pages\Admin\InsertRatePopUp.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ltlRateTextBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TMS;component/pages/admin/insertratepopup.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Pages\Admin\InsertRatePopUp.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.InsertRateButton = ((System.Windows.Controls.Button)(target));
            
            #line 18 "..\..\..\..\Pages\Admin\InsertRatePopUp.xaml"
            this.InsertRateButton.Click += new System.Windows.RoutedEventHandler(this.InsertRateButton_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.CancelRateButton = ((System.Windows.Controls.Button)(target));
            
            #line 19 "..\..\..\..\Pages\Admin\InsertRatePopUp.xaml"
            this.CancelRateButton.Click += new System.Windows.RoutedEventHandler(this.CancelRateButton_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.ClientNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.dCityTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.ftlaTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.ltlaTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.ftlRateTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.reefChargeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.ltlRateTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

