#pragma checksum "..\..\..\..\Pages\Planner\PlannerWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "44D7DA10BE3050A6D44AD4BE3727E5EF24D3A59D16BC21337FBB8F4077A487AE"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using TMS.Pages;


namespace TMS.Pages {
    
    
    /// <summary>
    /// PlannerWindow
    /// </summary>
    public partial class PlannerWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 23 "..\..\..\..\Pages\Planner\PlannerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LiveTimeLabel;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\Pages\Planner\PlannerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_ActiveOrdersRefresh;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\Pages\Planner\PlannerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_PendingOrdersRefresh;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\Pages\Planner\PlannerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox ActiveOrdersListBox;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\..\Pages\Planner\PlannerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox PendingOrdersListBox;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\..\Pages\Planner\PlannerWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SignOut;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TMS;component/pages/planner/plannerwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Pages\Planner\PlannerWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 22 "..\..\..\..\Pages\Planner\PlannerWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AddOneDay_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.LiveTimeLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 3:
            
            #line 24 "..\..\..\..\Pages\Planner\PlannerWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Generate_Summary_Report);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btn_ActiveOrdersRefresh = ((System.Windows.Controls.Button)(target));
            
            #line 26 "..\..\..\..\Pages\Planner\PlannerWindow.xaml"
            this.btn_ActiveOrdersRefresh.Click += new System.Windows.RoutedEventHandler(this.btn_ActiveOrdersRefreshClick);
            
            #line default
            #line hidden
            return;
            case 5:
            this.btn_PendingOrdersRefresh = ((System.Windows.Controls.Button)(target));
            
            #line 27 "..\..\..\..\Pages\Planner\PlannerWindow.xaml"
            this.btn_PendingOrdersRefresh.Click += new System.Windows.RoutedEventHandler(this.btn_PendingOrdersRefreshCick);
            
            #line default
            #line hidden
            return;
            case 6:
            this.ActiveOrdersListBox = ((System.Windows.Controls.ListBox)(target));
            
            #line 28 "..\..\..\..\Pages\Planner\PlannerWindow.xaml"
            this.ActiveOrdersListBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ActiveOrdersListBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 7:
            this.PendingOrdersListBox = ((System.Windows.Controls.ListBox)(target));
            
            #line 29 "..\..\..\..\Pages\Planner\PlannerWindow.xaml"
            this.PendingOrdersListBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.PendingOrdersListBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            
            #line 31 "..\..\..\..\Pages\Planner\PlannerWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.SignOut = ((System.Windows.Controls.Button)(target));
            
            #line 32 "..\..\..\..\Pages\Planner\PlannerWindow.xaml"
            this.SignOut.Click += new System.Windows.RoutedEventHandler(this.SignOutClick);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

